### ISSUE TITLE
Video lagging

### ISSUE THREAD

**Issue by freezaer** [RattenBonkers/TVLoader#1]
The video is lagging. I download mods through r2modman, mods for TV that use this mod as a dependency are very slow. Is it possible to fix this somehow?

**Comment by TheEvilSocks** [comment]
Heya, do you have an example of a mod with laggy videos? I've tried a few of the mods popular tv mods, but can't reproduce the issue.

**Comment by TheEvilSocks** [comment]
Gonna assume this is fixed, as I've received no reply.
